/**
 * api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Notice {
  
  @SerializedName("time")
  private Date time = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("detail")
  private String detail = null;

  /**
   * 时间
   **/
  @ApiModelProperty(value = "时间")
  public Date getTime() {
    return time;
  }
  public void setTime(Date time) {
    this.time = time;
  }

  /**
   * 标题
   **/
  @ApiModelProperty(required = true, value = "标题")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * 内容
   **/
  @ApiModelProperty(required = true, value = "内容")
  public String getDetail() {
    return detail;
  }
  public void setDetail(String detail) {
    this.detail = detail;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Notice notice = (Notice) o;
    return (this.time == null ? notice.time == null : this.time.equals(notice.time)) &&
        (this.title == null ? notice.title == null : this.title.equals(notice.title)) &&
        (this.detail == null ? notice.detail == null : this.detail.equals(notice.detail));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.time == null ? 0: this.time.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.detail == null ? 0: this.detail.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Notice {\n");
    
    sb.append("  time: ").append(time).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  detail: ").append(detail).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
