/**
 * api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SessionId {
  
  @SerializedName("sessionid")
  private String sessionid = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSessionid() {
    return sessionid;
  }
  public void setSessionid(String sessionid) {
    this.sessionid = sessionid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionId sessionId = (SessionId) o;
    return (this.sessionid == null ? sessionId.sessionid == null : this.sessionid.equals(sessionId.sessionid));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sessionid == null ? 0: this.sessionid.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionId {\n");
    
    sb.append("  sessionid: ").append(sessionid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
