/**
 * api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SportPlanInfo {
  
  @SerializedName("planId")
  private Integer planId = null;
  @SerializedName("cancelled")
  private Boolean cancelled = null;
  @SerializedName("startTime")
  private Date startTime = null;
  @SerializedName("endTime")
  private Date endTime = null;

  /**
   * 跑操计划的id
   **/
  @ApiModelProperty(required = true, value = "跑操计划的id")
  public Integer getPlanId() {
    return planId;
  }
  public void setPlanId(Integer planId) {
    this.planId = planId;
  }

  /**
   * 是否被取消
   **/
  @ApiModelProperty(value = "是否被取消")
  public Boolean getCancelled() {
    return cancelled;
  }
  public void setCancelled(Boolean cancelled) {
    this.cancelled = cancelled;
  }

  /**
   * 开始时间（精确到一天的一个时间点）
   **/
  @ApiModelProperty(required = true, value = "开始时间（精确到一天的一个时间点）")
  public Date getStartTime() {
    return startTime;
  }
  public void setStartTime(Date startTime) {
    this.startTime = startTime;
  }

  /**
   * 结束时间（精确到一天的一个时间点）
   **/
  @ApiModelProperty(required = true, value = "结束时间（精确到一天的一个时间点）")
  public Date getEndTime() {
    return endTime;
  }
  public void setEndTime(Date endTime) {
    this.endTime = endTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SportPlanInfo sportPlanInfo = (SportPlanInfo) o;
    return (this.planId == null ? sportPlanInfo.planId == null : this.planId.equals(sportPlanInfo.planId)) &&
        (this.cancelled == null ? sportPlanInfo.cancelled == null : this.cancelled.equals(sportPlanInfo.cancelled)) &&
        (this.startTime == null ? sportPlanInfo.startTime == null : this.startTime.equals(sportPlanInfo.startTime)) &&
        (this.endTime == null ? sportPlanInfo.endTime == null : this.endTime.equals(sportPlanInfo.endTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.planId == null ? 0: this.planId.hashCode());
    result = 31 * result + (this.cancelled == null ? 0: this.cancelled.hashCode());
    result = 31 * result + (this.startTime == null ? 0: this.startTime.hashCode());
    result = 31 * result + (this.endTime == null ? 0: this.endTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SportPlanInfo {\n");
    
    sb.append("  planId: ").append(planId).append("\n");
    sb.append("  cancelled: ").append(cancelled).append("\n");
    sb.append("  startTime: ").append(startTime).append("\n");
    sb.append("  endTime: ").append(endTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
