/**
 * api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SportTypeInfo {
  
  @SerializedName("sportTypeId")
  private Integer sportTypeId = null;
  @SerializedName("leastSportDays")
  private Integer leastSportDays = 45;
  @SerializedName("leastLengthKMOnceSport")
  private Double leastLengthKMOnceSport = 1.0;

  /**
   * 运动类型id
   **/
  @ApiModelProperty(required = true, value = "运动类型id")
  public Integer getSportTypeId() {
    return sportTypeId;
  }
  public void setSportTypeId(Integer sportTypeId) {
    this.sportTypeId = sportTypeId;
  }

  /**
   * 最少运动天数
   **/
  @ApiModelProperty(value = "最少运动天数")
  public Integer getLeastSportDays() {
    return leastSportDays;
  }
  public void setLeastSportDays(Integer leastSportDays) {
    this.leastSportDays = leastSportDays;
  }

  /**
   * 每次最少长度（KM）
   **/
  @ApiModelProperty(value = "每次最少长度（KM）")
  public Double getLeastLengthKMOnceSport() {
    return leastLengthKMOnceSport;
  }
  public void setLeastLengthKMOnceSport(Double leastLengthKMOnceSport) {
    this.leastLengthKMOnceSport = leastLengthKMOnceSport;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SportTypeInfo sportTypeInfo = (SportTypeInfo) o;
    return (this.sportTypeId == null ? sportTypeInfo.sportTypeId == null : this.sportTypeId.equals(sportTypeInfo.sportTypeId)) &&
        (this.leastSportDays == null ? sportTypeInfo.leastSportDays == null : this.leastSportDays.equals(sportTypeInfo.leastSportDays)) &&
        (this.leastLengthKMOnceSport == null ? sportTypeInfo.leastLengthKMOnceSport == null : this.leastLengthKMOnceSport.equals(sportTypeInfo.leastLengthKMOnceSport));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.sportTypeId == null ? 0: this.sportTypeId.hashCode());
    result = 31 * result + (this.leastSportDays == null ? 0: this.leastSportDays.hashCode());
    result = 31 * result + (this.leastLengthKMOnceSport == null ? 0: this.leastLengthKMOnceSport.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SportTypeInfo {\n");
    
    sb.append("  sportTypeId: ").append(sportTypeId).append("\n");
    sb.append("  leastSportDays: ").append(leastSportDays).append("\n");
    sb.append("  leastLengthKMOnceSport: ").append(leastLengthKMOnceSport).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
