/**
 * api documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Date;
import io.swagger.client.model.*;

public class JsonUtil {
  public static GsonBuilder gsonBuilder;

  static {
    gsonBuilder = new GsonBuilder();
    gsonBuilder.serializeNulls();
    gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    gsonBuilder.registerTypeAdapter(Date.class, new JsonDeserializer<Date>() {
      public Date deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return new Date(json.getAsJsonPrimitive().getAsLong());
      }
    });
  }

  public static Gson getGson() {
    return gsonBuilder.create();
  }

  public static String serialize(Object obj){
    return getGson().toJson(obj);
  }

  public static <T> T deserializeToList(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getListTypeForDeserialization(cls));
  }

  public static <T> T deserializeToObject(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getTypeForDeserialization(cls));
  }

  public static Type getListTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("AResult".equalsIgnoreCase(className)) {
      return new TypeToken<List<AResult>>(){}.getType();
    }
    
    if ("AdminInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<AdminInfo>>(){}.getType();
    }
    
    if ("ClassInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<ClassInfo>>(){}.getType();
    }
    
    if ("Notice".equalsIgnoreCase(className)) {
      return new TypeToken<List<Notice>>(){}.getType();
    }
    
    if ("SessionId".equalsIgnoreCase(className)) {
      return new TypeToken<List<SessionId>>(){}.getType();
    }
    
    if ("SportPlanInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<SportPlanInfo>>(){}.getType();
    }
    
    if ("SportRecordInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<SportRecordInfo>>(){}.getType();
    }
    
    if ("SportTypeInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<SportTypeInfo>>(){}.getType();
    }
    
    if ("StudentInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<StudentInfo>>(){}.getType();
    }
    
    if ("TeacherInfo".equalsIgnoreCase(className)) {
      return new TypeToken<List<TeacherInfo>>(){}.getType();
    }
    
    if ("TracePoint".equalsIgnoreCase(className)) {
      return new TypeToken<List<TracePoint>>(){}.getType();
    }
    
    return new TypeToken<List<Object>>(){}.getType();
  }

  public static Type getTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("AResult".equalsIgnoreCase(className)) {
      return new TypeToken<AResult>(){}.getType();
    }
    
    if ("AdminInfo".equalsIgnoreCase(className)) {
      return new TypeToken<AdminInfo>(){}.getType();
    }
    
    if ("ClassInfo".equalsIgnoreCase(className)) {
      return new TypeToken<ClassInfo>(){}.getType();
    }
    
    if ("Notice".equalsIgnoreCase(className)) {
      return new TypeToken<Notice>(){}.getType();
    }
    
    if ("SessionId".equalsIgnoreCase(className)) {
      return new TypeToken<SessionId>(){}.getType();
    }
    
    if ("SportPlanInfo".equalsIgnoreCase(className)) {
      return new TypeToken<SportPlanInfo>(){}.getType();
    }
    
    if ("SportRecordInfo".equalsIgnoreCase(className)) {
      return new TypeToken<SportRecordInfo>(){}.getType();
    }
    
    if ("SportTypeInfo".equalsIgnoreCase(className)) {
      return new TypeToken<SportTypeInfo>(){}.getType();
    }
    
    if ("StudentInfo".equalsIgnoreCase(className)) {
      return new TypeToken<StudentInfo>(){}.getType();
    }
    
    if ("TeacherInfo".equalsIgnoreCase(className)) {
      return new TypeToken<TeacherInfo>(){}.getType();
    }
    
    if ("TracePoint".equalsIgnoreCase(className)) {
      return new TypeToken<TracePoint>(){}.getType();
    }
    
    return new TypeToken<Object>(){}.getType();
  }

};
